#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=04:00:00

time singularity exec docker://brainlife/mrtrix3:3.0_RC3 create_NIFTI_maps.sh

# run the actual python code
time singularity exec docker://brainlife/dipy:latest python3 SNR_report.py
